In [1]:
import numpy as np

In [4]:
# Create a 3x3x3 array with random values
x=np.random.random((3,3,3))
print(x)

[[[0.00505015 0.98897807 0.94355809]
  [0.12744895 0.01336562 0.7916474 ]
  [0.23742252 0.22197426 0.17112828]]

 [[0.81839256 0.57984749 0.75325142]
  [0.73072206 0.33558831 0.60608816]
  [0.12006141 0.3986727  0.26390546]]

 [[0.34512384 0.81034612 0.96446477]
  [0.68547482 0.50731233 0.19156856]
  [0.419156   0.31752522 0.86683186]]]


In [16]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [64]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)





Checkerboard pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [36]:
# Normalize a 5x5 random matrix
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.48531769 0.23463666 0.08926528 0.73440115 0.73127901]
 [0.79683384 0.37429626 0.31446478 0.58827613 0.00848408]
 [0.68389518 0.44491004 0.41739642 0.88814829 0.66495459]
 [0.16833576 0.93301941 0.43231746 0.2876821  0.03787313]
 [0.16524164 0.61170231 0.30399177 0.15714322 0.7106113 ]]
After normalization:
[[0.51575488 0.24461216 0.08737492 0.78516964 0.78179266]
 [0.85269836 0.3956714  0.3309562  0.62711725 0.        ]
 [0.73054115 0.47204898 0.44228958 0.9514663  0.71005455]
 [0.17289949 1.         0.45842854 0.3019874  0.03178791]
 [0.16955281 0.65245558 0.31962834 0.16079336 0.75943796]]


In [44]:
#  How to find common values between two arrays?
import numpy as np
arr1=np.array(([1,3,5,7],[2,4,6,8]))
print("Array1",arr1)
arr2=np.array(([3,5,9,11],[4,8,10,12]))
print("Array2",arr2)
print("Common values between 2 arrays")
print(np.intersect1d(arr1,arr2))


Array1 [[1 3 5 7]
 [2 4 6 8]]
Array2 [[ 3  5  9 11]
 [ 4  8 10 12]]
Common values between 2 arrays
[3 4 5 8]


In [45]:
# How to get the dates of yesterday, today and tomorrow?
import datetime
today=datetime.date.today()
yesterday=today-datetime.timedelta(days=1)
tommorrow=today+datetime.timedelta(days=1)
print(today)
print(yesterday)
print(tommorrow)

2020-07-26
2020-07-25
2020-07-27


In [49]:
# Consider two random array A and B, check if they are equal
import numpy as np
arr1=np.array(([3,5,9,11]))
print("Array1",arr1)
arr2=np.array(([3,5,9,11]))
print("Array2",arr2)
arr_equal=np.allclose(arr1,arr2)
print(arr_equal)

Array1 [ 3  5  9 11]
Array2 [ 3  5  9 11]
True


In [50]:
# Create random vector of size 10 and replace the maximum value by 0
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.03970517 0.23840614 0.25123489 0.22496126 0.91865568 0.74499409
 0.100369   0.58540812 0.85558209 0.53418463]
Maximum value replaced by 0:
[0.03970517 0.23840614 0.25123489 0.22496126 0.         0.74499409
 0.100369   0.58540812 0.85558209 0.53418463]


In [51]:
# How to print all the values of an array?
import numpy as np
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [63]:
# Subtract the mean of each row of a matrix
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3,3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1)
print(Y)

Original matrix:

[[0.68010936 0.56837742 0.97813938]
 [0.92501349 0.2972868  0.47417919]
 [0.11582672 0.13437926 0.62043311]]

Subtract the mean of each row of the said matrix:

[[-0.06209936  0.00288425  0.68792635]
 [ 0.18280478 -0.26820636  0.18396616]
 [-0.626382   -0.4311139   0.33022008]]


In [75]:
 # .Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
    Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)


[5. 3. 3. 1. 4. 2. 5. 3. 2. 2.]


In [76]:
#How to find the most frequent value in an array?
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 5 4 6 9 9 2 7 4 7 5 2 4 2 5 3 2 1 6 4 0 5 3 7 1 4 0 8 1 1 3 2 0 9 4 1 7
 5 9 3]
Most frequent value in the above array:
4


In [77]:
# program to get the n largest values of an arr
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [79]:
# program to create a record array from a (flat) list of arrays.
import numpy as np
a1=np.array([5,6,7,8])
a2=np.array(['Red','Green','Blue','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(5, 'Red', 12.2)
(6, 'Green', 15.)
(7, 'Blue', 20.)
